### YamlMime:Yaml
ms.openlocfilehash: 095db29b6191a9dbacf1ace37dc0486510a01a20
ms.sourcegitcommit: 8b2f02dd5189c46ecff33c07223ed62b36842d34
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 07/08/2020
ms.locfileid: "3542518"
name: Begrüßungen
on:
  pull_request:
    branches:
    - live
  issues:
    branches:
    - live
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Hello, thanks for your feedback. We triage this feedback regularly and use it to plan for future documentation improvements. If you have a suggestion for a product idea, please go to [Ideas](https://aka.ms/bcideas).
        pr-message: Hello, thanks for your contribution, much appreciated. We will triage and review your PR as soon as possible.
